language: java
install: mvn -Drepo.username=${REPO_USERNAME} -Drepo.password=${REPO_PASSWORD} -Dfindbugs-maven-plugin.version=3.0.5 -s conf/maven_settings_idfc.xml install
script: mvn -Drepo.username=${REPO_USERNAME} -Drepo.password=${REPO_PASSWORD} -Dfindbugs-maven-plugin.version=3.0.5  -s conf/maven_settings_idfc.xml test
 # decrype the account key file
